### ISSUE TITLE
Personal roadmap for OSM

### ISSUE THREAD

**Issue by abitrolly** [osm-by/OpenStreetMap.by#12]
Improving OpenStreetMap.by service.
* [ ] add https
* [ ] add infrastructure configs - nginx, DB, redis (terraform, ansible if needed)
* [ ] add WSGI setup instead of FastCGI

Packing for local development.
* [ ] add explicit `static/` handler for `web.py` running in development mode
* [ ] restore config files needed to make the service work
* [ ] add files to containerize the app
* [ ] build and share containers through CI
* [ ] add a script to bring up development environment with a single command

Adding docs.
* [ ] define what this project is all about
* [ ] draw a diagram of components with ports
* [ ] explain how the server is different from main https://openstreetmap.org
* [ ] compare it with https://wiki.openstreetmap.org/wiki/OpenStreetMap-in-a-Box
* [ ] add licensing terms

Improving the code.
* [ ] port to Python 3 (because Python 2 is out of play)
