### ISSUE TITLE
Add overview tiles for planet

### ISSUE THREAD

**Issue by tbicr** [osm-by/OpenStreetMap.by#24]
## Description
Now only Belarus dump used to generate openmaptile mbtiles that don't show tiles for all world:

![image](https://user-images.githubusercontent.com/416731/110856003-26259780-82c8-11eb-8209-07f6b203f833.png)

*NOTE: openmaptile works next way: get osm dump (+ natural planet or other data) -> import it to PostGIS -> generate mbtiles by quering PostGIS*

To improve it whole planet dump can be used but it can have next issues:
- OSM dump itself take 70+ GB
- import to postgis take up to 24 hours
- imported postgis dump take 500+ GB
- mbtiles generation take 2000+ hours
- generated mbtiles take 70+ GB

## Approaches to solve this issues

1. try to avoid mbtile generation solve mbtiles issues but require 500+ GB postgis lunch and can have performance issues to generate tiles on fly (let assume we want to choose this option in case if don't have luck with mbtiles)
2. try to decrease mbtile zoom levels
3. try to remove mbtile features (by type or most heavy to generate)
4. try to filter unused features from OSM dump/PostGIS

## Steps
- [ ] Make sure that current tile generation mechanism works and generate tiles for small region (Belarus for example)
- [ ] Generate only boundary layer (https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml#L9) for planet and deploy
- [ ] Collect statistic about time and size generation for each layer (https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml) and zoom level (0-14) and extropalate it to whole planet
- [ ] Check how filtering OSM dump can improve generation

**Comment by tbicr** [comment]
added owerview tiles with no building and poi, for border tiles used planet tiles

**Comment by abitrolly** [comment]
I guess this is how it is done https://github.com/osm-by/OpenStreetMap.by/commit/a16601196eaaab8f6f42c6c425b6c12bd512d6f1
